### ISSUE TITLE
Certificates don't match

### ISSUE THREAD

**Issue by panama69** [hpe-apppulse/openapiclientdemo#1]
I was wondering if you encountered this before?

Starting getTokenFromAppPulseOpenAPI ... 
Using url: https://apppulse-mobile.saas.hpe.com:443/mobile/openapi/rest/v1/672149734/oauth/token
Failed to execute getTokenFromAppPulseOpenAPI:getToken
hostname in certificate didn't match: <apppulse-mobile.saas.hpe.com> != <_.saas.hp.com> OR <saas.hp.com> OR <_.saas.hp.com>... getTokenFromAppPulseOpenAPI - Completed
failed to authorise (get token)hostname in certificate didn't match: <apppulse-mobile.saas.hpe.com> != <_.saas.hp.com> OR <saas.hp.com> OR <_.saas.hp.com>

**Comment by m-seldin** [comment]
You are probably using the example code behind a proxy. I have modified the code to handle proxy settings passed in the cmd args to fix your problem.
Please update you code (pay attention that the usage has slightly changed)

(I am closing the issue, if you encourage any other problems please open a new one)
